sonar.projectKey=Kpoiut_CNPM
sonar.organization=kpoiut
sonar.projectName=Real Estate AVM
sonar.sources=src,frontend/src
sonar.tests=tests,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/__pycache__/**,docs/archive/**,src/models_archive/**
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
